version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env
